import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithCustomToken, signOut } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
const firebaseApp=initializeApp({apiKey:"AIzaSyDhyDoFRrCXXEkoQ3i6wpqmNd8Po6p_KIw",authDomain:"medhaclockin.firebaseapp.com",projectId:"medhaclockin",storageBucket:"medhaclockin.firebasestorage.app",messagingSenderId:"458648237732",appId:"1:458648237732:web:aadb89db358e0cca7b9831"});
const auth=getAuth(firebaseApp); let currentUserId=null; let currentAppUser=null; let launchAuthorized=false;
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const launchStorageKey="medha-communications-hub-token";
const launchToken=new URLSearchParams(location.hash.slice(1)).get("token")||sessionStorage.getItem(launchStorageKey);
const launchGate=$("#launch-gate");
const SUPABASE_URL="https://nnvyfeckimnjvmeneiro.supabase.co";
const SUPABASE_ANON_KEY="sb_publishable_H-o5HRFu3lCq5E9Hf1s3uA_Hi_LaMnY";
const headers={apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`};
let conversations=[];
let active=null;
async function db(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{...headers,"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok)throw Error(`Supabase ${r.status}`);if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
function avatar(c,small=false){return `<div class="person-avatar ${c.color||"blue"}${small?" small":""}">${esc(c.initials)}</div>`}
function renderList(){const q=$("#chat-search").value.toLowerCase();const favorites=JSON.parse(sessionStorage.getItem(`medha-favorites-${currentUserId||"guest"}`)||"[]");$("#chat-list").innerHTML=conversations.filter(c=>`${c.name} ${c.preview}`.toLowerCase().includes(q)).map(c=>`<div class="chat-item ${active&&c.id===active.id?"selected":""}" data-id="${c.id}"><div class="avatar-stack">${avatar(c)}${c.unread?'<i class="unread-dot"></i>':''}</div><div class="chat-copy"><div class="chat-line"><strong>${favorites.includes(c.id)?"☆ ":""}${esc(c.name)}</strong><time>${esc(c.time||"")}</time></div><p>${esc(c.preview||"")}</p></div></div>`).join("")||'<p class="empty">No conversations yet. Select + to start a chat.</p>';}
function renderMessages(){if(!active){$("#conversation-name").textContent="No conversation selected";$("#details-name").textContent="No conversation selected";$("#conversation-status").textContent="";$("#message-area").innerHTML='<div class="empty-state"><strong>No conversation selected</strong><p>Your real conversations will appear here after you start or receive a chat.</p></div>';return}$("#conversation-name").textContent=active.name;$("#details-name").textContent=active.name;$("#conversation-status").textContent=active.team||"";$(".conversation-header .person-avatar").outerHTML=avatar(active);$(".details-person .person-avatar").outerHTML=avatar(active);const allAttachments=active.messages.flatMap(m=>m.attachments||[]);$("#shared-media").innerHTML=allAttachments.length?allAttachments.map(a=>a.kind==="gif"?`<a href="${esc(a.url)}" target="_blank" rel="noopener">GIF</a>`:`<a href="${esc(a.url)}" target="_blank" rel="noopener">📎</a>`).join(""):"<div class=\"directory-empty\">No shared media</div>";$("#message-area").innerHTML='<div class="date-divider"><span>Conversation</span></div>'+active.messages.map(m=>{const links=(m.attachments||[]).length?m.attachments:(m.text||"").match(/https?:\/\/[^\s]+/g)?.filter(u=>/\.gif(?:$|\?)/i.test(u)||/giphy\.com|tenor\.com/i.test(u)).map(url=>({kind:"gif",url,name:"GIF"}))||[];return `<div class="message ${m.who==="me"?"mine":""}">${avatar(m.who==="me"?{initials:"",color:"blue"}:active,true)}<div class="message-body"><div class="message-meta"><strong>${m.who==="me"?"You":esc(active.name)}</strong><time>${esc(m.time)}</time></div>${m.text?`<div class="bubble">${esc(m.text)}</div>`:""}${links.map(a=>a.kind==="gif"?`<a class="message-gif" href="${esc(a.url)}" target="_blank" rel="noopener"><img src="${esc(a.url)}" alt="Attached GIF"></a>`:`<a class="message-file" href="${esc(a.url)}" target="_blank" rel="noopener">📎 ${esc(a.name)}</a>`).join("")}</div></div>`}).join("");$("#message-area").scrollTop=$("#message-area").scrollHeight}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
async function persistMessage(message){if(!currentUserId)throw Error("Sign in to Medha Hub before sending messages");let found=await db(`medha_communications_conversations?id=eq.${encodeURIComponent(active.id)}&select=id,participant_ids`);const participants=[...new Set([currentUserId,active.participantId,...(found?.[0]?.participant_ids||[])].filter(Boolean))];if(!found?.length){const row=await db("medha_communications_conversations",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({id:active.id,title:active.name,kind:"direct",participant_ids:participants,last_message:message.text||"Attachment"})});active.id=row?.[0]?.id||active.id}else if(JSON.stringify(found[0].participant_ids||[])!==JSON.stringify(participants)){await db(`medha_communications_conversations?id=eq.${encodeURIComponent(active.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({participant_ids:participants})})}const payload={conversation_id:active.id,sender_id:currentUserId,body:message.text||"Attachment",attachments:message.attachments||[]};try{await db("medha_communications_messages",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(payload)})}catch(error){const fallback={...payload,attachments:undefined,body:message.attachments?.length?`${payload.body}\n${message.attachments.map(a=>a.url).join("\n")}`:payload.body};await db("medha_communications_messages",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(fallback)})}await db(`medha_communications_conversations?id=eq.${encodeURIComponent(active.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({last_message:message.text||"Attachment",updated_at:new Date().toISOString()})})}
async function loadMessages(conversationId){try{return await db(`medha_communications_messages?conversation_id=eq.${encodeURIComponent(conversationId)}&select=sender_id,body,attachments,created_at&order=created_at.asc`)}catch(error){if(!String(error.message).includes("Supabase 400"))throw error;return await db(`medha_communications_messages?conversation_id=eq.${encodeURIComponent(conversationId)}&select=sender_id,body,created_at&order=created_at.asc`)}}
async function uploadFile(file){if(!currentUserId)throw Error("Sign in before attaching files");const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-");const path=`${currentUserId}/${crypto.randomUUID()}-${safe}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/medha-communications-files/${path.split("/").map(encodeURIComponent).join("/")}`,{method:"POST",headers:{...headers,"Content-Type":file.type||"application/octet-stream","x-upsert":"false"},body:file});if(!r.ok)throw Error(`Could not upload ${file.name}`);return {kind:"file",name:file.name,url:`${SUPABASE_URL}/storage/v1/object/public/medha-communications-files/${path.split("/").map(encodeURIComponent).join("/")}`}}
function switchChat(id){active=conversations.find(c=>c.id===id)||active;active.unread=0;renderList();renderMessages()}
function closeChatActions(){$("#chat-actions").hidden=true}function openChatActions(row,event){const menu=$("#chat-actions");menu.hidden=false;menu.dataset.chatId=row.dataset.id;menu.style.left=`${Math.min(event.clientX,window.innerWidth-220)}px`;menu.style.top=`${Math.min(event.clientY,window.innerHeight-150)}px`}$("#chat-list").addEventListener("click",e=>{const row=e.target.closest("[data-id]");if(row){closeChatActions();switchChat(row.dataset.id)}});$("#chat-list").addEventListener("dblclick",e=>{const row=e.target.closest("[data-id]");if(row)openChatActions(row,e)});document.addEventListener("click",e=>{if(!e.target.closest("#chat-actions")&&!e.target.closest(".chat-item"))closeChatActions()});$("#chat-actions").addEventListener("click",async e=>{const button=e.target.closest("[data-chat-action]");if(!button)return;const id=$("#chat-actions").dataset.chatId,c=conversations.find(x=>x.id===id);if(!c)return;if(button.dataset.chatAction==="favorite"){const key=`medha-favorites-${currentUserId||"guest"}`,items=JSON.parse(sessionStorage.getItem(key)||"[]"),next=items.includes(id)?items.filter(x=>x!==id):[...items,id];sessionStorage.setItem(key,JSON.stringify(next));renderList();toast(next.includes(id)?"Added to favorites":"Removed from favorites")}else if(button.dataset.chatAction==="unread"){c.unread=1;renderList();toast("Conversation marked unread")}else if(button.dataset.chatAction==="delete"){$("#delete-chat").click()}closeChatActions()});$("#chat-search").addEventListener("input",renderList);
$("#chat-list").addEventListener("contextmenu",e=>{const row=e.target.closest("[data-id]");if(!row)return;e.preventDefault();openChatActions(row,e)});
$("#chat-list").addEventListener("dblclick",e=>{const row=e.target.closest("[data-id]");if(!row)return;e.preventDefault();openChatActions(row,e)});
const chatDeleteAction=$("#chat-actions [data-chat-action=delete]");if(chatDeleteAction){chatDeleteAction.dataset.chatAction="pin";chatDeleteAction.textContent="📌 Pin chat"}$("#chat-actions").addEventListener("click",e=>{const button=e.target.closest('[data-chat-action="pin"]');if(!button)return;const id=$("#chat-actions").dataset.chatId,key=`medha-pinned-${currentUserId||"guest"}`,items=JSON.parse(sessionStorage.getItem(key)||"[]"),next=items.includes(id)?items.filter(x=>x!==id):[...items,id];sessionStorage.setItem(key,JSON.stringify(next));button.textContent=next.includes(id)?"📌 Unpin chat":"📌 Pin chat";toast(next.includes(id)?"Chat pinned":"Chat unpinned")});
let pendingAttachments=[];
function renderPending(){$("#pending-attachments").innerHTML=pendingAttachments.map((a,i)=>`<span class="attachment-chip">${a.kind==="gif"?"GIF":"📎"} ${esc(a.name||"GIF")} <button type="button" data-remove-attachment="${i}">×</button></span>`).join("")}
$("#attach-file").onclick=()=>$("#file-input").click();$("#file-input").addEventListener("change",async e=>{try{for(const file of e.target.files)pendingAttachments.push(await uploadFile(file));renderPending();e.target.value=""}catch(err){toast(err.message)}});$("#pending-attachments").addEventListener("click",e=>{const b=e.target.closest("[data-remove-attachment]");if(b){pendingAttachments.splice(Number(b.dataset.removeAttachment),1);renderPending()}});
const emojiGroups={"Smileys & people":"😀 😃 😄 😁 😆 😅 😂 🤣 😊 😇 🙂 🙃 😉 😌 😍 🥰 😘 😗 😙 😚 😋 😛 😝 😜 🤪 🤨 🧐 🤓 😎 🤩 🥳 😏 😒 😞 😔 😟 😕 🙁 ☹️ 😣 😖 😫 😩 🥺 😢 😭 😤 😠 😡 🤬 🤯 😳 🥵 🥶 😱 😨 😰 😥 😓 🤗 🤔 🫡 🤭 🤫 🤥 😶 😐 😑 😬 🙄 😯 😦 😧 😮 😲 🥱 😴 🤤 😪 😵 🤐 🤑 🤠 😈 👿 👹 👺 🤡 💩 👻 💀 ☠️ 👽 👾 🤖 🎃 😺 😸 😹 😻 😼 😽 🙀 😿 😾 🙌 👏 🤝 👍 👎 👌 ✌️ 🤞 🤟 🤘 👈 👉 👆 👇 ☝️ ✋ 🤚 🖐️ 🖖 👋 💪 🙏 👀 👁️ 👄 💋 💯" ,"Animals & nature":"🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 🐨 🐯 🦁 🐮 🐷 🐸 🐵 🐔 🐧 🐦 🐤 🦄 🐝 🦋 🐌 🐞 🐜 🕷️ 🦂 🐢 🐍 🦎 🦖 🐙 🦀 🐠 🐟 🐡 🐬 🐳 🐋 🦈 🐊 🐅 🐆 🦓 🦍 🐘 🦏 🦒 🦘 🦬 🐄 🐎 🐖 🐑 🦙 🐐 🐕 🐈 🐓 🦃 🕊️ 🐇 🐿️ 🦔 🌸 🌹 🌻 🌞 🌝 🌈 ⭐ 🌟 ✨ ⚡ 🔥 🌊 🍀 🌱 🌲 🌴 🌵 🍁" ,"Food & activities":"🍏 🍎 🍐 🍊 🍋 🍌 🍉 🍇 🍓 🫐 🍒 🍑 🥭 🍍 🥥 🥝 🍅 🥑 🍞 🧀 🍔 🍟 🍕 🌭 🌮 🌯 🥗 🍿 🍩 🍪 🎂 🍰 🍫 🍭 ☕ 🍺 🍻 🍷 🥂 ⚽ 🏀 🏈 ⚾ 🎾 🏐 🏆 🎮 🎲 🎯 🎨 🎵 🎶 🎤 🎬 🚗 🚕 🚌 🚆 ✈️ 🚀 🚲 ⛵" ,"Objects & symbols":"❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔 ❣️ 💕 💞 💓 💗 💖 💘 💝 💟 ✅ ❌ ❗ ❓ ‼️ ⁉️ ⚠️ 🚫 💡 🔒 🔓 🔑 🔔 🎁 🎈 🎉 🎊 📌 📎 📝 📅 📁 📂 💻 🖥️ 📱 ☎️ ⌚ 🔍 🔗 🛠️ ⚙️ 🔥 💬 🗨️ 💤 ✔️ ➕ ➖ ➡️ ⬆️ ⬇️"};
let allEmojis=Object.entries(emojiGroups).flatMap(([group,value])=>value.split(" ").map(emoji=>({group,emoji})));function renderEmojiPicker(query=""){const q=query.toLowerCase();$("#emoji-grid").innerHTML=allEmojis.filter(x=>!q||x.emoji.includes(q)||x.group.toLowerCase().includes(q)).map(x=>`<button type="button" class="emoji-choice" data-emoji="${x.emoji}" title="${x.group}">${x.emoji}</button>`).join("")||'<div class="directory-empty">No emoji found</div>'}$("#emoji-button").onclick=()=>{$("#emoji-dialog").showModal();renderEmojiPicker();$("#emoji-search").focus()};$("#close-emoji").onclick=()=>$("#emoji-dialog").close();$("#emoji-search").addEventListener("input",e=>renderEmojiPicker(e.target.value));$("#emoji-grid").addEventListener("click",e=>{const b=e.target.closest("[data-emoji]");if(b){$("#message-input").value+=b.dataset.emoji;$("#message-input").focus();$("#emoji-dialog").close()}});$("#gif-button").onclick=()=>$("#gif-dialog").showModal();$("#gif-form").addEventListener("submit",e=>{if(e.submitter?.value==="cancel"){e.target.closest("dialog").close();return}e.preventDefault();const url=$("#gif-url").value.trim();try{const parsed=new URL(url);if(!["http:","https:"].includes(parsed.protocol))throw Error();pendingAttachments.push({kind:"gif",name:"GIF",url:parsed.href});renderPending();$("#gif-url").value="";$("#gif-dialog").close()}catch{toast("Enter a valid GIF URL")}});
$("#message-input").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.isComposing){e.preventDefault();$("#composer").requestSubmit()}});
$("#composer").addEventListener("submit",async e=>{e.preventDefault();if(!active){toast("Select a conversation first");return}const input=$("#message-input"),text=input.value.trim();if(!text&&!pendingAttachments.length)return;const m={who:"me",text,attachments:[...pendingAttachments],time:"Just now"};try{await persistMessage(m);active.messages.push(m);active.preview=text||"Attachment";active.time="Just now";renderMessages();renderList();input.value="";pendingAttachments=[];renderPending();toast("Message sent")}catch(err){toast(err.message)}});
$("#open-details").onclick=()=>{$("#details-panel").classList.remove("closed");$("#details-panel").classList.add("open")};$("#close-details").onclick=()=>{$("#details-panel").classList.remove("open");$("#details-panel").classList.add("closed")};
$("#delete-chat").onclick=async()=>{if(!confirm(`Delete the conversation with ${active.name}? This permanently deletes all messages.`))return;try{await db(`medha_communications_messages?conversation_id=eq.${encodeURIComponent(active.id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});await db(`medha_communications_conversations?id=eq.${encodeURIComponent(active.id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}})}catch(e){console.info("Delete will sync when the communications schema is installed")};conversations=conversations.filter(c=>c.id!==active.id);active=conversations[0]||{id:"empty",name:"No conversation",initials:"—",color:"blue",team:"",messages:[]};renderList();renderMessages();$("#details-panel").classList.remove("open");toast("Conversation and messages deleted")};
$("#delete-chat")?.remove();let directory=[];let selectedEmployee=null;
async function loadEmployeeDirectory(){try{const rows=await db("users?select=id,full_name,email,department,role,is_active&is_active=eq.true&order=full_name.asc");directory=(rows||[]).filter(x=>x.full_name);renderDirectory("")}catch{directory=[];$("#employee-list").innerHTML='<div class="directory-empty">Employee directory unavailable. Connect Supabase to continue.</div>'}}
function renderDirectory(query){const list=$("#employee-list"),q=query.toLowerCase();const matches=directory.filter(p=>`${p.full_name} ${p.email||""} ${p.department||""}`.toLowerCase().includes(q));list.innerHTML=matches.length?matches.map(p=>`<button type="button" class="employee-option" data-person-id="${esc(p.id)}" data-person="${esc(p.full_name)}"><div class="person-avatar blue">${esc(p.full_name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase())}</div><div><strong>${esc(p.full_name)}</strong><small>${esc(p.department||p.role||"Medha employee")} · ${esc(p.email||"")}</small></div></button>`).join(""):"<div class=\"directory-empty\">No Medha employees found</div>"}
const eventInvitees=new Set(),eventInviteeSearch=$("#event-invitees"),eventInviteeList=document.createElement("div");eventInviteeList.className="employee-list event-invitee-list";eventInviteeSearch.placeholder="Search Medha employees to invite...";eventInviteeSearch.after(eventInviteeList);function renderEventInvitees(query=""){const q=query.toLowerCase();const matches=directory.filter(p=>`${p.full_name} ${p.email||""} ${p.department||""}`.toLowerCase().includes(q));eventInviteeList.innerHTML=matches.length?matches.map(p=>`<button type="button" class="employee-option ${eventInvitees.has(p.id)?"selected":""}" data-event-person-id="${esc(p.id)}"><div class="person-avatar blue">${esc(initialsFor(p.full_name))}</div><div><strong>${esc(p.full_name)}</strong><small>${esc(p.department||p.role||"Medha employee")} · ${esc(p.email||"")}</small></div><span class="invite-check">${eventInvitees.has(p.id)?"✓":""}</span></button>`).join(""):"<div class=\"directory-empty\">No Medha employees found</div>"}eventInviteeSearch.addEventListener("input",e=>renderEventInvitees(e.target.value));eventInviteeList.addEventListener("click",e=>{const button=e.target.closest("[data-event-person-id]");if(!button)return;const id=button.dataset.eventPersonId;if(eventInvitees.has(id))eventInvitees.delete(id);else eventInvitees.add(id);eventInviteeSearch.value="";eventInviteeSearch.value=[...eventInvitees].join(",");renderEventInvitees("")});$("#new-event").onclick=async()=>{$("#event-dialog").showModal();eventInvitees.clear();eventInviteeSearch.value="";await loadEmployeeDirectory();renderEventInvitees("")};
$("#new-chat").onclick=()=>{$("#new-chat-dialog").showModal();$("#new-chat-person").value="";selectedEmployee=null;loadEmployeeDirectory()};$("#new-chat-person").addEventListener("input",e=>{selectedEmployee=null;renderDirectory(e.target.value)});$("#employee-list").addEventListener("click",e=>{const option=e.target.closest("[data-person]");if(option){selectedEmployee=directory.find(p=>p.id===option.dataset.personId);$("#new-chat-person").value=option.dataset.person;document.querySelectorAll(".employee-option").forEach(x=>x.classList.remove("selected"));option.classList.add("selected")}});$("#new-chat-form").addEventListener("submit",async e=>{e.preventDefault();if(!selectedEmployee){toast("Select an employee from the directory");return}const name=selectedEmployee.full_name,text=$("#new-chat-message").value.trim(),key=crypto.randomUUID(),c={id:key,name,participantId:selectedEmployee.id,initials:name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase(),color:"blue",team:selectedEmployee.department||"",preview:text,time:"Now",messages:[]};try{if(text){const m={who:"me",text,time:"Just now"};await persistMessage({...m});c.messages.push(m)}else await db("medha_communications_conversations",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({id:key,title:name,kind:"direct",participant_ids:[selectedEmployee.id],last_message:""})});conversations.unshift(c);active=c;renderList();renderMessages();$("#new-chat-dialog").close();$("#new-chat-message").value="";toast("New chat started")}catch(err){toast(err.message)}});
let meetings=[];let calendarCursor=new Date();
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();$("#calendar-month").textContent=calendarCursor.toLocaleDateString([], {month:"long",year:"numeric"});const first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate(),cells=[];for(let i=0;i<first;i++)cells.push('<div class="muted"></div>');for(let d=1;d<=last;d++){const date=new Date(y,m,d),key=date.toISOString().slice(0,10),items=meetings.filter(x=>x.start.slice(0,10)===key);cells.push(`<div class="${key===new Date().toISOString().slice(0,10)?"today":""}">${d}${items.map(x=>`<i title="${esc(x.title)}">${esc(x.title)}</i>`).join("")}</div>`)}$("#calendar-grid").innerHTML=cells.join("")||'<div class="empty-state">No scheduled meetings.</div>';const future=meetings.filter(x=>new Date(x.start)>=new Date()).sort((a,b)=>new Date(a.start)-new Date(b.start));$("#agenda-list").innerHTML=future.length?future.map(x=>`<div class="agenda-item"><b>${new Date(x.start).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</b><div><strong>${esc(x.title)}</strong><span>${new Date(x.start).toLocaleDateString([], {weekday:"short",month:"short",day:"numeric"})}</span></div></div>`).join(""):"<div class=\"empty-state\">No upcoming meetings.</div>"}
async function loadMeetings(){try{meetings=await db(`medha_communications_meetings?select=id,title,start_at,end_at,invitee_ids&order=start_at.asc`)||[];meetings=meetings.map(x=>({...x,start:String(x.start_at||"")}));renderCalendar()}catch{meetings=[];renderCalendar()}}
$("#calendar-prev").onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()};$("#calendar-next").onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()};$("#calendar-today").onclick=()=>{calendarCursor=new Date();renderCalendar()};$("#new-event").onclick=()=>$("#event-dialog").showModal();$("#event-form").addEventListener("submit",async e=>{if(e.submitter?.value==="cancel"){e.target.closest("dialog").close();return}e.preventDefault();if(!currentUserId){toast("Sign in to create meetings");return}const title=$("#event-title").value.trim(),start=$("#event-start").value,end=$("#event-end").value;if(new Date(end)<=new Date(start)){toast("End time must be after start time");return}try{await db("medha_communications_meetings",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({title,start_at:new Date(start).toISOString(),end_at:new Date(end).toISOString(),invitee_ids:$("#event-invitees").value.split(",").map(x=>x.trim()).filter(Boolean),created_by:currentUserId})});$("#event-dialog").close();e.target.reset();await loadMeetings();toast("Meeting created")}catch(err){toast(err.message)}});
function openEventForCalendarDate(day){const date=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth(),day,9,0);const end=new Date(date);end.setHours(10);const localValue=value=>{const pad=n=>String(n).padStart(2,"0");return `${value.getFullYear()}-${pad(value.getMonth()+1)}-${pad(value.getDate())}T${pad(value.getHours())}:${pad(value.getMinutes())}`};$("#event-form").reset();$("#event-start").value=localValue(date);$("#event-end").value=localValue(end);$("#event-dialog").showModal()}
$("#calendar-grid").addEventListener("dblclick",event=>{const cell=event.target.closest("#calendar-grid>div");if(!cell||cell.classList.contains("muted"))return;const first=(new Date(calendarCursor.getFullYear(),calendarCursor.getMonth(),1).getDay()+6)%7;const day=[...$("#calendar-grid").children].indexOf(cell)-first+1;if(day>0)openEventForCalendarDate(day)});
document.querySelectorAll("#event-start,#event-end").forEach(input=>input.addEventListener("click",()=>input.showPicker?.()));document.querySelectorAll("dialog .close-dialog").forEach(button=>button.addEventListener("click",()=>button.closest("dialog").close()));
document.querySelectorAll('dialog button[value="cancel"]').forEach(button=>button.addEventListener("click",event=>{event.preventDefault();button.closest("dialog")?.close()}));
$("#new-event").onclick=async()=>{$("#event-dialog").showModal();eventInvitees.clear();eventInviteeSearch.value="";await loadEmployeeDirectory();renderEventInvitees("")};
document.querySelectorAll(".composer-tools button,.header-action,.team-card,.page-head .primary-button,.page-head .secondary-button").forEach(el=>el.addEventListener("click",()=>{if(el.id!=="new-chat"&&el.id!=="new-event"&&el.dataset.view===undefined)toast(el.title||"This workspace action is ready") }));
document.querySelectorAll(".rail-item[data-view]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".rail-item").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.remove("active-view"));const view=document.getElementById(`${b.dataset.view}-view`);if(view)view.classList.add("active-view");const shell=document.querySelector(".app-shell");shell.classList.toggle("calendar-mode",b.dataset.view==="calendar");$("#chat-sidebar").style.display=b.dataset.view==="chat"?"flex":"none";if(b.dataset.view==="chat")$("#details-panel").classList.remove("closed");else{$("#details-panel").classList.remove("open");$("#details-panel").classList.add("closed")} });
function setWorkspaceView(viewName){
  document.querySelectorAll(".rail-item[data-view]").forEach(item=>item.classList.toggle("active",item.dataset.view===viewName));
  document.querySelectorAll(".view").forEach(view=>{
    const activeView=view.id===`${viewName}-view`;
    view.classList.toggle("active-view",activeView);
    view.hidden=!activeView;
    view.style.display=activeView?"flex":"none";
  });
  const shell=document.querySelector(".app-shell");
  shell.classList.toggle("calendar-mode",viewName==="calendar");
  $("#chat-sidebar").style.display=viewName==="chat"?"flex":"none";
  const calendarSidebar=$("#calendar-sidebar");calendarSidebar.hidden=viewName!=="calendar";calendarSidebar.style.display=viewName==="calendar"?"flex":"none";if(viewName==="calendar")shell.style.gridTemplateColumns="80px 280px minmax(500px,1fr) 0";else shell.style.removeProperty("grid-template-columns");
  if(viewName==="chat") $("#details-panel").classList.remove("closed");
  else { $("#details-panel").classList.remove("open"); $("#details-panel").classList.add("closed"); }
  if(viewName==="calendar") renderCalendar();
}
document.querySelectorAll(".rail-item[data-view]").forEach(item=>item.onclick=()=>setWorkspaceView(item.dataset.view));
setWorkspaceView("chat");
renderCalendar();
async function hydrateFromSupabase(){try{const rows=await db("medha_communications_conversations?select=id,title,kind,last_message,updated_at,participant_ids&order=updated_at.desc");const loaded=await Promise.all((rows||[]).map(async row=>{const messages=await loadMessages(row.id);return {id:row.id,name:row.title,participantId:(row.participant_ids||[])[0],initials:row.title.split(/\\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase(),color:row.kind==="channel"?"amber":"blue",team:row.kind==="channel"?"Team channel":"",preview:row.last_message||"",time:row.updated_at?new Date(row.updated_at).toLocaleDateString([], {month:"short",day:"numeric"}):"",messages:(messages||[]).map(m=>({who:m.sender_id===currentUserId?"me":"them",text:m.body,attachments:m.attachments||[],time:new Date(m.created_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}))};}));conversations=loaded;active=conversations[0]||null;renderList();renderMessages()}catch(e){conversations=[];active=null;renderList();renderMessages();toast(`Supabase communications is unavailable: ${e.message}`)}}
async function hydrateConversationsForUser(){try{const [rows,people]=await Promise.all([db("medha_communications_conversations?select=id,title,kind,last_message,updated_at,participant_ids&order=updated_at.desc"),db("users?select=id,full_name")]);const viewerIds=new Set([currentUserId,currentAppUser?.id].filter(Boolean));const loaded=await Promise.all((rows||[]).map(async row=>{const messages=await loadMessages(row.id),ids=[...new Set([...(row.participant_ids||[]),...(messages||[]).map(m=>m.sender_id).filter(Boolean)])],otherId=ids.find(id=>!viewerIds.has(id)),other=people?.find(person=>person.id===otherId),name=other?.full_name||(row.kind==="channel"?row.title:"Conversation");return {id:row.id,name,participantId:otherId,initials:initialsFor(name),color:row.kind==="channel"?"amber":"blue",team:row.kind==="channel"?"Team channel":"",preview:row.last_message||"",time:row.updated_at?new Date(row.updated_at).toLocaleDateString([], {month:"short",day:"numeric"}):"",messages:(messages||[]).map(m=>({who:viewerIds.has(m.sender_id)?"me":"them",text:m.body,attachments:m.attachments||[],time:new Date(m.created_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}))};}));conversations=loaded;const previousId=active?.id;active=conversations.find(c=>c.id===previousId)||conversations[0]||null;renderList();renderMessages()}catch(e){conversations=[];active=null;renderList();renderMessages();toast(`Supabase communications is unavailable: ${e.message}`)}}
function initialsFor(name){return String(name||"").trim().split(/\s+/).filter(Boolean).map(part=>part[0]).join("").slice(0,2).toUpperCase()}
let syncInProgress=false;
async function syncIncomingMessages(){if(!currentUserId||syncInProgress)return;syncInProgress=true;try{await hydrateConversationsForUser()}finally{syncInProgress=false}}
setInterval(syncIncomingMessages,5000);
async function loadCurrentProfile(user){if(!user)return;try{const rows=await db(`users?id=eq.${encodeURIComponent(user.uid)}&select=id,full_name,email,department,role,is_active`);currentAppUser=rows?.[0]||null;const name=currentAppUser?.full_name||user.displayName||user.email||"Signed-in user";$("#current-user").textContent=name;$("#current-user-initials").textContent=initialsFor(currentAppUser?.full_name||user.displayName||user.email)}catch{const name=user.displayName||user.email||"Signed-in user";$("#current-user").textContent=name;$("#current-user-initials").textContent=initialsFor(user.displayName||user.email)}}
async function initializeAuthorizedUser(user){if(!user)return;currentUserId=user.uid;$("#current-user").textContent=user.displayName||user.email||"Authenticating…";await loadCurrentProfile(user);await Promise.all([hydrateConversationsForUser(),loadMeetings()])}
async function authorizeHubLaunch(){if(!launchToken){launchGate.hidden=false;return}try{const r=await fetch("/api/hub-session",{method:"POST",headers:{Authorization:`Bearer ${launchToken}`}});if(!r.ok)throw Error();const {customToken}=await r.json();sessionStorage.setItem(launchStorageKey,launchToken);launchAuthorized=true;const signedIn=await signInWithCustomToken(auth,customToken);await initializeAuthorizedUser(signedIn.user);launchGate.hidden=true;history.replaceState(null,"",location.pathname+location.search)}catch{launchAuthorized=false;sessionStorage.removeItem(launchStorageKey);await signOut(auth).catch(()=>{});launchGate.hidden=false}}
onAuthStateChanged(auth,user=>{if(!launchAuthorized){currentUserId=null;return}if(user)initializeAuthorizedUser(user);else{$("#current-user").textContent="Authentication required"}});
const reactionLoadMessages=loadMessages;loadMessages=async conversationId=>{try{return await db(`medha_communications_messages?conversation_id=eq.${encodeURIComponent(conversationId)}&select=id,sender_id,body,attachments,reactions,created_at&order=created_at.asc`)}catch(error){if(!String(error.message).includes("Supabase 400"))throw error;return await reactionLoadMessages(conversationId)}};
const baseRenderMessages=renderMessages;async function renderStoredReactions(conversationId){const rows=await db(`medha_communications_messages?conversation_id=eq.${encodeURIComponent(conversationId)}&select=id,reactions&order=created_at.asc`),messages=[...$("#message-area").querySelectorAll(".message")];messages.forEach((row,index)=>{row.querySelectorAll(".stored-reactions").forEach(node=>node.remove());const reactions=rows?.[index]?.reactions||{},items=Object.entries(reactions).filter(([,users])=>Array.isArray(users)&&users.length);if(!items.length)return;const badge=document.createElement("div");badge.className="stored-reactions";badge.innerHTML=items.map(([emoji,users])=>`<span title="${users.length} reaction${users.length===1?"":"s"}">${emoji}${users.length>1?` ${users.length}`:""}</span>`).join("");row.querySelector(".message-body")?.append(badge)})}
renderMessages=()=>{baseRenderMessages();if(active?.id)renderStoredReactions(active.id).catch(()=>{})};
const locationInput=document.createElement("input");locationInput.id="event-location";locationInput.maxLength=240;locationInput.placeholder="Optional meeting location";const locationLabel=document.createElement("label");locationLabel.textContent="Meeting location";locationLabel.append(locationInput);const locationTags=document.createElement("div");locationTags.className="location-tags";locationTags.innerHTML='<button type="button" data-location-tag="Online">Online</button><button type="button" data-location-tag="Office">Office</button>';locationLabel.append(locationTags);$("#event-invitees").closest("label").before(locationLabel);locationTags.addEventListener("click",e=>{const tag=e.target.closest("[data-location-tag]");if(tag)locationInput.value=tag.dataset.locationTag});window.addEventListener("communications:add-suggestion-event",event=>{const d=event.detail||{},dateText=String(d.start||""),dateMatch=dateText.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/)||dateText.match(/([A-Za-z]{3,9})\s+(\d{1,2})(?:.*?(\d{4}))?/),date=dateMatch?(dateMatch[3]?new Date(+dateMatch[3],+dateMatch[1]-1,+dateMatch[2]):new Date(`${dateMatch[1]} ${dateMatch[2]}, ${dateMatch[3]||new Date().getFullYear()}`)):new Date(),timeMatch=String(d.time||"").match(/(\d{1,2})(?::(\d{2}))?\s*(AM|PM)/i),hour=timeMatch?(+timeMatch[1]%12)+(timeMatch[3].toUpperCase()==="PM"?12:0):9,minute=timeMatch?+(timeMatch[2]||0):0,pad=n=>String(n).padStart(2,"0"),value=`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(hour)}:${pad(minute)}`;$("#event-form").reset();$("#event-title").value=d.title||"";$("#event-start").value=value;const end=new Date(date);end.setHours(hour+1,minute,0,0);$("#event-end").value=`${end.getFullYear()}-${pad(end.getMonth()+1)}-${pad(end.getDate())}T${pad(end.getHours())}:${pad(end.getMinutes())}`;locationInput.value=d.location&&d.location!=="Not published"?d.location:"";$("#event-dialog").showModal()});
$("#event-title").closest("label").childNodes[0].textContent="Event Title";$("#event-title").placeholder="Event title";
const communicationsDb=db;db=async(path,options={})=>{if(path==="medha_communications_meetings"&&options.method==="POST"&&options.body){const payload=JSON.parse(options.body);payload.location=$("#event-location")?.value.trim()||null;options={...options,body:JSON.stringify(payload)}}return communicationsDb(path,options)};
authorizeHubLaunch();
const calendarRender=renderCalendar;renderCalendar=function(){calendarRender();const list=$("#calendar-sidebar-list"),future=meetings.filter(x=>x.start&&new Date(x.start)>=new Date()).sort((a,b)=>new Date(a.start)-new Date(b.start));if(list)list.innerHTML=future.length?future.map(x=>`<div class="calendar-side-event"><time>${new Date(x.start).toLocaleDateString([], {month:"short",day:"numeric"})}</time><div><strong>${esc(x.title||"Meeting")}</strong><span>${new Date(x.start).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</span></div></div>`).join(""):"<div class=\"empty-state\">No upcoming meetings.</div>"};
function externalStartDate(value){const text=String(value||""),numeric=text.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/),named=text.match(/([A-Za-z]{3,9})\s+(\d{1,2})(?:.*?(\d{4}))?/);if(numeric)return new Date(Number(numeric[3]),Number(numeric[1])-1,Number(numeric[2]));if(named){const year=Number(named[3]||new Date().getFullYear()),date=new Date(`${named[1]} ${named[2]}, ${year}`);if(!Number.isNaN(date.getTime()))return date}return null}
async function loadSuggestions(){const list=$("#suggestions-list");try{const [eventsResponse,exhibitionsResponse]=await Promise.all([fetch("https://medha-newsevents.vercel.app/api/events"),fetch("https://medha-newsevents.vercel.app/api/exhibitions")]);if(!eventsResponse.ok||!exhibitionsResponse.ok)throw Error("Events & News unavailable");const [events,exhibitions]=await Promise.all([eventsResponse.json(),exhibitionsResponse.json()]),items=[...(events.sources||[]).flatMap(source=>(source.items||[]).map(item=>({...item,kind:"Event"}))),...(exhibitions.sources||[]).flatMap(source=>(source.items||[]).map(item=>({...item,kind:"Exhibition"})))].map(item=>({...item,start:externalStartDate(item.date)})).filter(item=>item.start&&item.start>=new Date()).sort((a,b)=>a.start-b.start).slice(0,20);list.innerHTML=items.length?items.map(item=>`<a class="suggestion-item" href="${esc(item.link||"https://medha-newsevents.vercel.app/")}" target="_blank" rel="noopener"><span>${item.kind}</span><strong>${esc(item.title)}</strong><time>${item.start.toLocaleDateString([], {month:"short",day:"numeric",year:"numeric"})}</time></a>`).join(""):"<div class=\"empty-state\">No upcoming events or exhibitions.</div>"}catch{list.innerHTML='<div class="empty-state">Events &amp; News is unavailable.</div>'}}
const reactionMenu=document.createElement("div");reactionMenu.className="reaction-menu";reactionMenu.hidden=true;reactionMenu.innerHTML=["👍","❤️","😂","😮","😢","🎉"].map(emoji=>`<button type="button" data-reaction="${emoji}">${emoji}</button>`).join("");document.body.append(reactionMenu);let reactionTarget=null;$("#message-area").addEventListener("dblclick",e=>{const row=e.target.closest(".message");if(!row||!active)return;e.preventDefault();reactionTarget=row;reactionMenu.hidden=false;reactionMenu.style.left=`${Math.min(e.clientX,window.innerWidth-250)}px`;reactionMenu.style.top=`${Math.max(12,e.clientY-55)}px`});document.addEventListener("click",e=>{if(!e.target.closest(".reaction-menu")&&!e.target.closest(".message"))reactionMenu.hidden=true});reactionMenu.addEventListener("click",async e=>{const button=e.target.closest("[data-reaction]");if(!button||!reactionTarget||!active)return;const messageIndex=[...$("#message-area").querySelectorAll(".message")].indexOf(reactionTarget),rows=await db(`medha_communications_messages?conversation_id=eq.${encodeURIComponent(active.id)}&select=id,reactions&order=created_at.asc`),record=rows?.[messageIndex];if(!record){toast("Message could not be found");return}const reactions=record.reactions&&typeof record.reactions==="object"?record.reactions:{};Object.keys(reactions).forEach(key=>{reactions[key]=(Array.isArray(reactions[key])?reactions[key]:[]).filter(id=>id!==currentUserId);if(!reactions[key].length)delete reactions[key]});reactions[button.dataset.reaction]=[...(reactions[button.dataset.reaction]||[]),currentUserId];try{await db(`medha_communications_messages?id=eq.${encodeURIComponent(record.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({reactions})});const pill=reactionTarget.querySelector(".reaction");if(pill)pill.textContent=button.dataset.reaction;else{const next=document.createElement("span");next.className="reaction";next.textContent=button.dataset.reaction;reactionTarget.querySelector(".message-body").append(next)}toast("Reaction added")}catch(err){toast(err.message)}reactionMenu.hidden=true});loadSuggestions();
