import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
const firebaseApp=initializeApp({apiKey:"AIzaSyDhyDoFRrCXXEkoQ3i6wpqmNd8Po6p_KIw",authDomain:"medhaclockin.firebaseapp.com",projectId:"medhaclockin",storageBucket:"medhaclockin.firebasestorage.app",messagingSenderId:"458648237732",appId:"1:458648237732:web:aadb89db358e0cca7b9831"});
const auth=getAuth(firebaseApp); let currentUserId=null;
const SUPABASE_URL="https://nnvyfeckimnjvmeneiro.supabase.co";
const SUPABASE_ANON_KEY="sb_publishable_H-o5HRFu3lCq5E9Hf1s3uA_Hi_LaMnY";
const headers={apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`};
let conversations=[];
let active=null;
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function db(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{...headers,"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok)throw Error(`Supabase ${r.status}`);if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
function avatar(c,small=false){return `<div class="person-avatar ${c.color||"blue"}${small?" small":""}">${esc(c.initials)}</div>`}
function renderList(){const q=$("#chat-search").value.toLowerCase();$("#chat-list").innerHTML=conversations.filter(c=>`${c.name} ${c.preview}`.toLowerCase().includes(q)).map(c=>`<div class="chat-item ${active&&c.id===active.id?"selected":""}" data-id="${c.id}"><div class="avatar-stack">${avatar(c)}</div><div class="chat-copy"><div class="chat-line"><strong>${esc(c.name)}</strong><time>${esc(c.time||"")}</time></div><p>${esc(c.preview||"")}</p></div></div>`).join("")||'<p class="empty">No conversations yet. Select + to start a chat.</p>';}
function renderMessages(){if(!active){$("#conversation-name").textContent="No conversation selected";$("#details-name").textContent="No conversation selected";$("#conversation-status").textContent="";$("#message-area").innerHTML='<div class="empty-state"><strong>No conversation selected</strong><p>Your real conversations will appear here after you start or receive a chat.</p></div>';return}$("#conversation-name").textContent=active.name;$("#details-name").textContent=active.name;$("#conversation-status").textContent=active.team||"";$(".conversation-header .person-avatar").outerHTML=avatar(active);$(".details-person .person-avatar").outerHTML=avatar(active);$("#message-area").innerHTML='<div class="date-divider"><span>Conversation</span></div>'+active.messages.map(m=>`<div class="message ${m.who==="me"?"mine":""}">${avatar(m.who==="me"?{initials:"",color:"blue"}:active,true)}<div class="message-body"><div class="message-meta"><strong>${m.who==="me"?"You":esc(active.name)}</strong><time>${esc(m.time)}</time></div><div class="bubble">${esc(m.text)}</div></div></div>`).join("");$("#message-area").scrollTop=$("#message-area").scrollHeight}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
async function persistMessage(message){if(!currentUserId)throw Error("Sign in to Medha Hub before sending messages");let found=await db(`medha_communications_conversations?id=eq.${encodeURIComponent(active.id)}&select=id`);if(!found?.length){const row=await db("medha_communications_conversations",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({id:active.id,title:active.name,kind:"direct",participant_ids:active.participantId?[active.participantId]:[],last_message:message.text})});active.id=row?.[0]?.id||active.id}await db("medha_communications_messages",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({conversation_id:active.id,sender_id:currentUserId,body:message.text})})}
function switchChat(id){active=conversations.find(c=>c.id===id)||active;active.unread=0;renderList();renderMessages()}
$("#chat-list").addEventListener("click",e=>{const row=e.target.closest("[data-id]");if(row)switchChat(row.dataset.id)});$("#chat-search").addEventListener("input",renderList);
$("#composer").addEventListener("submit",async e=>{e.preventDefault();const input=$("#message-input"),text=input.value.trim();if(!text)return;const m={who:"me",text,time:"Just now"};active.messages.push(m);active.preview=text;active.time="Just now";renderMessages();renderList();input.value="";await persistMessage(m);toast("Message sent")});
$("#open-details").onclick=()=>$("#details-panel").classList.toggle("open");$("#close-details").onclick=()=>$("#details-panel").classList.remove("open");
$("#delete-chat").onclick=async()=>{if(!confirm(`Delete the conversation with ${active.name}? This permanently deletes all messages.`))return;try{await db(`medha_communications_messages?conversation_id=eq.${encodeURIComponent(active.id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});await db(`medha_communications_conversations?id=eq.${encodeURIComponent(active.id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}})}catch(e){console.info("Delete will sync when the communications schema is installed")};conversations=conversations.filter(c=>c.id!==active.id);active=conversations[0]||{id:"empty",name:"No conversation",initials:"—",color:"blue",team:"",messages:[]};renderList();renderMessages();$("#details-panel").classList.remove("open");toast("Conversation and messages deleted")};
let directory=[];let selectedEmployee=null;
async function loadEmployeeDirectory(){try{const rows=await db("users?select=id,full_name,email,department,role,is_active&is_active=eq.true&order=full_name.asc");directory=(rows||[]).filter(x=>x.full_name);renderDirectory("")}catch{directory=[];$("#employee-list").innerHTML='<div class="directory-empty">Employee directory unavailable. Connect Supabase to continue.</div>'}}
function renderDirectory(query){const list=$("#employee-list"),q=query.toLowerCase();const matches=directory.filter(p=>`${p.full_name} ${p.email||""} ${p.department||""}`.toLowerCase().includes(q));list.innerHTML=matches.length?matches.map(p=>`<button type="button" class="employee-option" data-person-id="${esc(p.id)}" data-person="${esc(p.full_name)}"><div class="person-avatar blue">${esc(p.full_name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase())}</div><div><strong>${esc(p.full_name)}</strong><small>${esc(p.department||p.role||"Medha employee")} · ${esc(p.email||"")}</small></div></button>`).join(""):"<div class=\"directory-empty\">No Medha employees found</div>"}
$("#new-chat").onclick=()=>{$("#new-chat-dialog").showModal();$("#new-chat-person").value="";selectedEmployee=null;loadEmployeeDirectory()};$("#new-chat-person").addEventListener("input",e=>{selectedEmployee=null;renderDirectory(e.target.value)});$("#employee-list").addEventListener("click",e=>{const option=e.target.closest("[data-person]");if(option){selectedEmployee=directory.find(p=>p.id===option.dataset.personId);$("#new-chat-person").value=option.dataset.person;document.querySelectorAll(".employee-option").forEach(x=>x.classList.remove("selected"));option.classList.add("selected")}});$("#new-chat-form").addEventListener("submit",async e=>{e.preventDefault();if(!selectedEmployee){toast("Select an employee from the directory");return}const name=selectedEmployee.full_name,text=$("#new-chat-message").value.trim(),key=crypto.randomUUID(),c={id:key,name,participantId:selectedEmployee.id,initials:name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase(),color:"blue",team:selectedEmployee.department||"",preview:text,time:"Now",messages:[]};try{if(text){const m={who:"me",text,time:"Just now"};await persistMessage({...m});c.messages.push(m)}else await db("medha_communications_conversations",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({id:key,title:name,kind:"direct",participant_ids:[selectedEmployee.id],last_message:""})});conversations.unshift(c);active=c;renderList();renderMessages();$("#new-chat-dialog").close();$("#new-chat-message").value="";toast("New chat started")}catch(err){toast(err.message)}});
$("#new-event").onclick=()=>toast("Event creation is ready to connect to your shared calendar");
document.querySelectorAll(".composer-tools button,.header-action,.team-card,.page-head .primary-button,.page-head .secondary-button").forEach(el=>el.addEventListener("click",()=>{if(el.id!=="new-chat"&&el.id!=="new-event"&&el.dataset.view===undefined)toast(el.title||"This workspace action is ready") }));
document.querySelectorAll(".rail-item[data-view]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".rail-item").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.remove("active-view"));$(`#${b.dataset.view}-view`).classList.add("active-view");$("#chat-sidebar").style.display=b.dataset.view==="chat"?"flex":"none"});
$("#calendar-grid").innerHTML='<div class="empty-state">No scheduled meetings.</div>';
async function hydrateFromSupabase(){try{const rows=await db("medha_communications_conversations?select=id,title,kind,last_message,updated_at,participant_ids&order=updated_at.desc");const loaded=await Promise.all((rows||[]).map(async row=>{const messages=await db(`medha_communications_messages?conversation_id=eq.${encodeURIComponent(row.id)}&select=sender_id,body,created_at&order=created_at.asc`);return {id:row.id,name:row.title,participantId:(row.participant_ids||[])[0],initials:row.title.split(/\\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase(),color:row.kind==="channel"?"amber":"blue",team:row.kind==="channel"?"Team channel":"",preview:row.last_message||"",time:row.updated_at?new Date(row.updated_at).toLocaleDateString([], {month:"short",day:"numeric"}):"",messages:(messages||[]).map(m=>({who:m.sender_id===currentUserId?"me":"them",text:m.body,time:new Date(m.created_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}))};}));conversations=loaded;active=conversations[0]||null;renderList();renderMessages()}catch(e){conversations=[];active=null;renderList();renderMessages();toast("Supabase communications is unavailable")}}
onAuthStateChanged(auth,user=>{currentUserId=user?.uid||null;hydrateFromSupabase()});
