-- ============================================================
-- Medha Space — compact conversation storage.
-- Run AFTER supabase-communications-migration.sql.
--
-- Shape (exactly the model you asked for):
--
--   conversations        one row per thread
--   messages             one row per message, all messages for a thread
--                        share that thread's conversation id
--   user_conversations   which conversation ids each user can see
--
--   Opening Space for user 4 = one read of user_conversations for their
--   conversation ids, then one read of messages for those ids.
--
-- What this removes:
--   * user_chats.display_name  — the name is on users.full_name already,
--                                and was stored once PER PARTICIPANT
--   * user_chats.last_message  — a copy of conversations.last_message,
--                                also stored once per participant
--   * user_chats.updated_at    — same, derivable from the conversation
--   * conversations.title      — for direct chats the title is just the
--                                other person's name; kept only for channels
--   * the 61-byte text conversation id repeated in every message row,
--     replaced by a bigint surrogate key
-- ============================================================

begin;

-- ---------- 1. compact conversation key ----------
-- 'dm_<28-char uid>__<28-char uid>' is ~61 bytes and is repeated on every
-- message row and every membership row. A bigint is 8.
alter table public.medha_communications_conversations
  add column if not exists cid bigint generated by default as identity;
create unique index if not exists medha_conversations_cid_idx
  on public.medha_communications_conversations(cid);

-- The natural key stays as a unique constraint so the client can still
-- resolve a direct chat from the two uids without a lookup table.
alter table public.medha_communications_conversations
  drop constraint if exists medha_conversations_key_unique;
alter table public.medha_communications_conversations
  add constraint medha_conversations_key_unique unique (id);

-- ---------- 2. messages point at the compact key ----------
alter table public.medha_communications_messages
  add column if not exists cid bigint;
update public.medha_communications_messages m
  set cid = c.cid
  from public.medha_communications_conversations c
  where c.id = m.conversation_id and m.cid is null;
alter table public.medha_communications_messages
  alter column cid set not null;
alter table public.medha_communications_messages
  drop constraint if exists medha_messages_cid_fkey;
alter table public.medha_communications_messages
  add constraint medha_messages_cid_fkey
  foreign key (cid) references public.medha_communications_conversations(cid)
  on delete cascade;

-- One index serves the only message query the app makes:
-- "this thread's messages, newest first, paged".
drop index if exists public.medha_communications_messages_conversation_idx;
drop index if exists public.medha_communications_messages_conv_created_idx;
create index if not exists medha_messages_thread_idx
  on public.medha_communications_messages(cid, created_at desc, id desc);

-- ---------- 3. membership table: ids only ----------
create table if not exists public.medha_communications_user_conversations (
  user_id text not null,
  cid bigint not null references public.medha_communications_conversations(cid) on delete cascade,
  primary key (user_id, cid)
);
alter table public.medha_communications_user_conversations enable row level security;

insert into public.medha_communications_user_conversations(user_id,cid)
  select distinct participant, c.cid
  from public.medha_communications_conversations c
  cross join lateral unnest(c.participant_ids) participant
  where participant is not null and participant <> ''
  on conflict do nothing;

-- Ordering comes from the conversation, so membership needs no timestamp.
create index if not exists medha_user_conversations_user_idx
  on public.medha_communications_user_conversations(user_id);

-- ---------- 4. keep membership in step with participants ----------
create or replace function public.medha_communications_sync_membership() returns trigger
language plpgsql as $$
begin
  delete from public.medha_communications_user_conversations
    where cid = new.cid and not (user_id = any(new.participant_ids));
  insert into public.medha_communications_user_conversations(user_id,cid)
    select p, new.cid from unnest(new.participant_ids) p
    where p is not null and p <> ''
    on conflict do nothing;
  return new;
end; $$;

drop trigger if exists medha_communications_sync_user_chats_trigger
  on public.medha_communications_conversations;
drop trigger if exists medha_communications_sync_membership_trigger
  on public.medha_communications_conversations;
create trigger medha_communications_sync_membership_trigger
  after insert or update of participant_ids on public.medha_communications_conversations
  for each row execute function public.medha_communications_sync_membership();

-- ---------- 5. conversation preview kept in one place ----------
-- last_message/updated_at live only on the conversation row and are
-- maintained by the database, so the client stops issuing a PATCH per send.
create or replace function public.medha_communications_touch_conversation() returns trigger
language plpgsql as $$
begin
  update public.medha_communications_conversations
    set last_message = left(new.body, 120),
        updated_at   = new.created_at
    where cid = new.cid;
  return new;
end; $$;
drop trigger if exists medha_communications_touch_conversation_trigger
  on public.medha_communications_messages;
create trigger medha_communications_touch_conversation_trigger
  after insert on public.medha_communications_messages
  for each row execute function public.medha_communications_touch_conversation();

-- A preview never needs the whole body.
alter table public.medha_communications_conversations
  alter column last_message type varchar(120);

-- ---------- 6. drop the duplicated membership table ----------
drop table if exists public.medha_communications_user_chats;

-- ---------- 7. one read for the whole sidebar ----------
-- The client selects from this view with a single user_id filter and gets
-- each conversation id, the other participant, and the preview.
create or replace view public.medha_communications_my_conversations as
  select uc.user_id,
         c.cid,
         c.id           as conversation_key,
         c.kind,
         c.title,
         c.participant_ids,
         c.last_message,
         c.updated_at
  from public.medha_communications_user_conversations uc
  join public.medha_communications_conversations c on c.cid = uc.cid;

commit;

-- ---------- housekeeping ----------
-- Run these SEPARATELY, outside the transaction above and outside busy hours:
-- VACUUM FULL rewrites the table and holds an ACCESS EXCLUSIVE lock, so the
-- app cannot read or write while it runs. Plain VACUUM is safe any time but
-- returns the space to Postgres rather than the filesystem.
--
--   vacuum (analyze) public.medha_communications_conversations;
--   vacuum (analyze) public.medha_communications_messages;
--
-- Only if you need the disk back:
--   vacuum full public.medha_communications_conversations;
--   vacuum full public.medha_communications_messages;
